{
 "name": "Gestion des étudiants",
 "version": "0.8",
 "category": "Generic Modules/Others",
 "description": """ Test création module gestion des étudiants Odoo v14""",
 "author": "Moi",
 "data": ["data/students_training_data.xml",
"data/students_student_data.xml",
"views/students_views.xml",
"views/training_views.xml",
"views/mark_views.xml",],
 "depends": ["base"],
 "installable": True,
 "auto_install": False,
}
